#!/bin/bash
sudo chattr -i /etc/resolv.conf
sudo su -c "echo '# Generated by NetworkManager' >> /etc/resolv.conf"
sudo su -c "echo 'nameserver 127.0.0.1' >> /etc/resolv.conf"
sudo su -c "echo '# Google DNS' >> /etc/resolv.conf"
sudo su -c "echo 'nameserver 8.8.8.8' >> /etc/resolv.conf"
sudo su -c "echo 'nameserver 8.8.4.4' >> /etc/resolv.conf"
sudo sed -r -i ':1;N;s/^(.+)((\n.*)*)\n\1$/\1\2/M;$!b1' /etc/resolv.conf
sudo chattr +i /etc/resolv.conf

#这个+i的选项就是为文件 /etc/resolv.conf 添加了写保护，因此任何人都不可以修改

#需要取消写保护，使用下面的命令：
#sudo chattr -i /etc/resolv.conf
